### ISSUE TITLE
New Grooveshark Interface

### ISSUE THREAD

**Issue by Fubar69** [UlysseM/GSBOT#26]
Will we be able to use the bot with the new style of grooveshark interface anytime soon?

**Comment by UlysseM** [comment]
I shall work on it asap... it might be an ugly patch though, as I'm focusing on something a bit different for the future of the bot.

**Comment by Fubar69** [comment]
Can you let me in on what you are working on?

**Comment by UlysseM** [comment]
The new bot should come out on monday, The browser extension will be deprecated (unless someone feels like maintaining it).

It will consist of a standalone running on nodejs, with really easy plugin support (in order to add all the feature you want without having to change one single line of the core), the API should be quite simple for anyone to use, will eat WAY less bandwidth, as well as way less ram and CPU power.

It will be quite easy to host multiple broadcast on the same machine.

In the meantime, sorry for the downtime.

**Comment by Fubar69** [comment]
How is it going on this? Is there anything I can do? How do I get the new bot to work?

**Comment by UlysseM** [comment]
I'm polishing up my code before my commit. It should be available in a matter of hours.

**Comment by UlysseM** [comment]
Done.
