### ISSUE TITLE
Peek

### ISSUE THREAD

**Issue by Fubar69** [UlysseM/GSBOT#32]
The peek command shows the album name in brackets. Is it possible to toggle to the artist?

**Comment by pironic** [comment]
While you're working on /peek, can you restrict to last 10 as well. similar output we had last time.

**Comment by UlysseM** [comment]
Done, and done!

Take a look at the new peek.js file, and the "config" field.

Each of the element can be overwritten in the main config.js file. For instance, if I want to show the artist name instead of the album name, I just need to put this as my config.

module.exports = {
 username: 'test@email.com', // Fill this with your grooveshark email / username
 password: 'YOURPASS', // Fill this with your grooveshark password
 plugins: {
    default: {
        peek: {
            peekArtist: true
        }
    }
 }
};

------

In the long terms, any plugins should be self sufficient in terms of default configuration. If you want to let the choice to a user, he can overload one or all the parameters easily.
