### ISSUE TITLE
LOW: problem with SymLink creation in enabelplugins.

### ISSUE THREAD

**Issue by pironic** [UlysseM/GSBOT#38]
can't tell if its because the network drive doesn't support symlinks in this fashion, in which case we should error check that, or if its a problem with the script. Either way, low priority. 

![image](https://cloud.githubusercontent.com/assets/541154/6738133/9dc92868-ce35-11e4-8a22-3e4a27c73903.png)

**Comment by pironic** [comment]
funny enough... also problem on ubuntu: 
![image](https://cloud.githubusercontent.com/assets/541154/6738226/4bd3ddf4-ce36-11e4-8107-3affe29e2388.png)

**Comment by UlysseM** [comment]
The symbolic link can only be done on a NTFS filesystem on windows (probably won't work with the network), and on the same partition in a linux drive.

A quick fix (for you) would be to copy the directory instead of doing a symbolic link, but you'll have to copy it at each update.

For your ubuntu, I have no idea, it definitely comes from nodejs itself (it works fine on my debian with their repository), and it has probably be patched by now (try to update nodejs and your packages).

**Comment by UlysseM** [comment]
I'm moving away from symbolic link with the new system, thus that issue should go away.

**Comment by Reanmachine** [comment]
I know I've had issues with POSIX environments emulated on windows (Cygwin/MSYS), you can use the option `--no-bin-links` when you create I think and they interop better inside the POSIX environment, if you still want to use symlinks.

**Comment by UlysseM** [comment]
I moved away from it with version 2.0.7Beta. The idea was to allow user to easily enable and disable their plugin. Most had to run a configuration, and it had to be a separate config to get the admin rights on windows to create a symbolic link.

It's now enabled through the configuraiton, and still has a script in order to configure it for people scared editing JSON.
