### ISSUE TITLE
Configurable threshold for /skip to be open to anyone

### ISSUE THREAD

**Issue by Reanmachine** [UlysseM/GSBOT#44]
Say a song goes -10 and there's a lot of unhappy people in the channel with a song (random / accident left in while a Guest isn't around) it would be nice to have /skip or /next or something open to everyone. Could be as simple as adding a isCurrentSongBelowVoteThreshold permission or something...

**Comment by pironic** [comment]
I'll look into the ability to overload a current plugin with the same command, or maybe executing both plugins. I'll do some testing and see what i can't make :-) 

I still have a few other plugins that i consider priority over this though. 
- Event Silence
- Contests/Roll
- Scheduled Callouts

**Comment by Reanmachine** [comment]
You could just make a new permission that's not based on the user, but a certain set of conditions. Or just implement it as /voteskip, perhaps as it's own isolated plugin.

**Comment by pironic** [comment]
I think it'd be better to just check the current condition and give the command to everyone.

permission: ['isListener'],

if (condition is met)  { do stuff }
else { return }

**Comment by Reanmachine** [comment]
Isn't that effectively what permissions are? Pre-conditions with a true/false state determining if you can run a command?

**Comment by UlysseM** [comment]
I thought that a while back, and I'm against for a few reasons:
1/ Broadcaster is run by guest, not by listeners: If you have "troll", one person could create 10 account come and downvote it, and skip every. single. track. making your broadcast unstable.
2/ If the song was played from your collection, well, it's your collection...
3/ If a song was accepted by a guest, chances are he is still arounds whenever it plays.

~~~~~~~
Right now, the bot is having the following security:
1/ Whitelisted can: make permanent change to the broadcast/account (touch the collection)
2/ Guests can: do stuff that will affect the current broadcast. They can at worst make a broadcast suck for as long as they are guest (by playing bad track / skipping every songs)
3/ People we follow can become guest
4/ listeners can do some commands such as stat, or anything that will NOT affect any listener not looking at the chat.

That being said, feel free to make a plugin with a /emergencySkip command, only doable when some %age of trusted listeners (that came here often, and sometimes upvote songs) are all downvoting, etc. It just won't be in the default plugin, and I'd suggest you to think it in order to avoid any vulnerability.
